### ISSUE TITLE
mysql里存的全是？

### ISSUE THREAD

**Issue by StevenIIV** [HoffmanZheng/Multi-Threaded-Crawler#11]

**Comment by HoffmanZheng** [comment]
可以根据目录：
Multi-Threaded-Crawler/src/main/resources/db/migration/
下的 sql 语句进行相关建表，或者 `mvn flyway:migrate`

**Comment by HoffmanZheng** [comment]
> _No description provided._

可以根据目录：
Multi-Threaded-Crawler/src/main/resources/db/migration/
下的 sql 语句进行相关建表，或者 mvn flyway:migrate
